version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8100:8100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ionic serve --host=0.0.0.0 --port=8100 --disableHostCheck

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
    - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/bin/bash", "ollama-entrypoint.sh"]

  whisper:
    build: ./whisper
    ports:
      - "5002:5002"
    volumes:
      - ./whisper:/app

volumes:
  pg_data:
  ollama_data:
